import React, { useState } from 'react';
import { useApp } from '../context/AppContext';
import { 
  FileText, 
  Download, 
  Printer, 
  Calendar, 
  UserCheck, 
  AlertTriangle,
  Briefcase,
  CheckCircle,
  FileCheck2,
  Cpu
} from 'lucide-react';

const Reports = () => {
  const { incidents, activeIncidentId, setActiveIncidentId, activeIncident } = useApp();
  const [downloading, setDownloading] = useState(false);

  if (!activeIncident) {
    return (
      <div className="p-8 text-center text-gray-400 font-mono">
        Loading RCA reports...
      </div>
    );
  }

  const handlePrint = () => {
    window.print();
  };

  const handleMockDownload = () => {
    setDownloading(true);
    
    // Simulate compilation
    setTimeout(() => {
      setDownloading(false);
      
      // Build a simple markdown report and download it
      const report = `# ROOT CAUSE ANALYSIS (RCA) - ${activeIncident.id}
Incident Name: ${activeIncident.shortName}
Severity: ${activeIncident.severity}
Status: ${activeIncident.status}
Detected Date: ${activeIncident.time}

## 1. EXECUTIVE SUMMARY
${activeIncident.rcaReport.executiveSummary}

## 2. ROOT CAUSE IDENTIFICATION
${activeIncident.rcaReport.rootCause}

## 3. BUSINESS IMPACT ANALYSIS
${activeIncident.rcaReport.businessImpact}

## 4. IMMEDIATE CORRECTIVE ACTIONS
${activeIncident.rcaReport.correctiveActions.map((c, i) => `${i + 1}. ${c}`).join('\n')}

## 5. PREVENTIVE REMEDIATION MEASURES
${activeIncident.rcaReport.preventiveActions.map((p, i) => `${i + 1}. ${p}`).join('\n')}

---
Generated by SmartOps AI Incident Platform - ${new Date().toLocaleDateString()}`;

      const blob = new Blob([report], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `RCA_Report_${activeIncident.id}.md`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    }, 1000);
  };

  return (
    <div className="space-y-6">
      
      {/* Title bar */}
      <div className="flex flex-col lg:flex-row justify-between items-start lg:items-center gap-4 p-5 rounded-2xl glass-panel border border-white/5 shadow-glass no-print">
        <div>
          <div className="flex items-center gap-2 text-indigo-400 font-bold text-xs uppercase tracking-wider">
            <FileText className="w-4 h-4" />
            <span>Root Cause Analysis (RCA) Registry</span>
          </div>
          <h2 className="text-2xl font-extrabold text-gray-100 mt-1">
            Incident Reports
          </h2>
        </div>
        
        <div className="flex flex-wrap items-center gap-3">
          <label className="text-xs text-gray-400 font-mono">Select RCA:</label>
          <select
            value={activeIncidentId}
            onChange={(e) => setActiveIncidentId(e.target.value)}
            className="pl-3 pr-8 py-2 text-xs font-mono font-bold rounded-lg bg-white/5 border border-white/10 text-gray-200 outline-none cursor-pointer appearance-none min-w-[220px]"
          >
            {incidents.map((inc) => (
              <option key={inc.id} value={inc.id} className="bg-bg-darker text-gray-200">
                {inc.id}: {inc.shortName}
              </option>
            ))}
          </select>
          
          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 px-3 py-2 text-xs font-bold rounded-lg bg-white/5 hover:bg-white/10 border border-white/10 text-gray-300 transition-all cursor-pointer"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print</span>
          </button>

          <button
            onClick={handleMockDownload}
            disabled={downloading}
            className="flex items-center gap-1.5 px-4 py-2 text-xs font-bold rounded-lg bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white shadow-glow-indigo transition-all cursor-pointer"
          >
            {downloading ? (
              <span className="w-3.5 h-3.5 rounded-full border border-white/20 border-t-white animate-spin"></span>
            ) : (
              <Download className="w-3.5 h-3.5" />
            )}
            <span>Export RCA</span>
          </button>
        </div>
      </div>

      {/* Printable Report Panel */}
      <div className="p-8 rounded-2xl glass-panel border border-white/5 shadow-glass space-y-8 print-container relative overflow-hidden bg-bg-card">
        {/* Glow watermark for premium design */}
        <div className="absolute -top-10 -right-10 w-40 h-40 bg-indigo-500/5 blur-3xl pointer-events-none rounded-full no-print"></div>
        
        {/* Report Header */}
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 pb-6 border-b border-white/10">
          <div>
            <div className="flex items-center gap-2">
              <span className="text-xs font-bold font-mono tracking-wider text-indigo-400 bg-indigo-500/10 px-2 py-0.5 rounded border border-indigo-500/20">OFFICIAL REPORT</span>
              <span className="text-[10px] text-gray-500 font-mono">ISSUED BY SMARTOPS AGENTS</span>
            </div>
            <h3 className="text-xl font-extrabold text-gray-100 mt-2">
              Root Cause Analysis Report
            </h3>
            <p className="text-xs text-gray-400 font-mono mt-0.5">{activeIncident.name}</p>
          </div>
          <div className="flex flex-col items-start sm:items-end text-xs font-mono text-gray-400 space-y-1.5">
            <div className="flex items-center gap-1.5">
              <Calendar className="w-3.5 h-3.5 text-indigo-400" />
              <span>Detected: {activeIncident.time}</span>
            </div>
            <div className="flex items-center gap-1.5">
              <UserCheck className="w-3.5 h-3.5 text-indigo-400" />
              <span>Responder: SRE Agent Pool</span>
            </div>
          </div>
        </div>

        {/* Info Grid */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 p-4 rounded-xl bg-white/5 border border-white/5 text-center font-mono">
          <div>
            <span className="text-[10px] text-gray-500 uppercase tracking-wider">Incident ID</span>
            <div className="text-sm font-bold text-indigo-400 mt-1">{activeIncident.id}</div>
          </div>
          <div>
            <span className="text-[10px] text-gray-500 uppercase tracking-wider">Severity</span>
            <div className={`text-sm font-bold mt-1 ${
              activeIncident.severity === 'CRITICAL' ? 'text-rose-400' :
              activeIncident.severity === 'HIGH' ? 'text-amber-400' : 'text-emerald-400'
            }`}>{activeIncident.severity}</div>
          </div>
          <div>
            <span className="text-[10px] text-gray-500 uppercase tracking-wider">Scope Status</span>
            <div className="text-sm font-bold text-gray-200 mt-1">{activeIncident.status}</div>
          </div>
          <div>
            <span className="text-[10px] text-gray-500 uppercase tracking-wider">System Category</span>
            <div className="text-sm font-bold text-gray-200 mt-1">{activeIncident.category}</div>
          </div>
        </div>

        {/* RCA Sections */}
        <div className="space-y-6">
          
          {/* Section 1: Executive Summary */}
          <div className="space-y-2">
            <h4 className="text-xs font-bold text-indigo-400 font-mono uppercase tracking-wider flex items-center gap-2 border-l-2 border-indigo-500 pl-2">
              1. Executive Summary
            </h4>
            <p className="text-sm text-gray-300 leading-relaxed pl-3">
              {activeIncident.rcaReport.executiveSummary}
            </p>
          </div>

          {/* Section 2: Root Cause */}
          <div className="space-y-2">
            <h4 className="text-xs font-bold text-indigo-400 font-mono uppercase tracking-wider flex items-center gap-2 border-l-2 border-indigo-500 pl-2">
              2. Root Cause Analysis
            </h4>
            <div className="p-4 rounded-xl bg-rose-500/5 border border-rose-500/10 flex gap-3 items-start pl-3">
              <AlertTriangle className="w-5 h-5 text-rose-400 shrink-0 mt-0.5" />
              <p className="text-sm text-gray-200 leading-relaxed font-semibold">
                {activeIncident.rcaReport.rootCause}
              </p>
            </div>
          </div>

          {/* Section 3: Business Impact */}
          <div className="space-y-2">
            <h4 className="text-xs font-bold text-indigo-400 font-mono uppercase tracking-wider flex items-center gap-2 border-l-2 border-indigo-500 pl-2">
              3. Business & Traffic Impact
            </h4>
            <div className="p-4 rounded-xl bg-white/5 border border-white/5 flex gap-3 items-start pl-3">
              <Briefcase className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
              <div className="space-y-1 text-sm text-gray-300 leading-relaxed">
                <p>{activeIncident.rcaReport.businessImpact}</p>
                <div className="text-xs font-mono text-gray-400 mt-2 flex items-center gap-4">
                  <span>Impact Index: {activeIncident.impactScore}/10</span>
                  <span>Active Users Affected: {activeIncident.activeUsersAffected}</span>
                </div>
              </div>
            </div>
          </div>

          {/* Section 4: Corrective Actions */}
          <div className="space-y-2">
            <h4 className="text-xs font-bold text-indigo-400 font-mono uppercase tracking-wider flex items-center gap-2 border-l-2 border-indigo-500 pl-2">
              4. Immediate Corrective Actions Mitigated
            </h4>
            <div className="space-y-2 pl-3">
              {activeIncident.rcaReport.correctiveActions.map((action, idx) => (
                <div key={idx} className="flex gap-2.5 items-start text-xs text-gray-300">
                  <CheckCircle className="w-4 h-4 text-emerald-500 shrink-0 mt-0.5" />
                  <p className="leading-relaxed">{action}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Section 5: Preventive Actions */}
          <div className="space-y-2">
            <h4 className="text-xs font-bold text-indigo-400 font-mono uppercase tracking-wider flex items-center gap-2 border-l-2 border-indigo-500 pl-2">
              5. Long-term Preventive Remediation
            </h4>
            <div className="space-y-2 pl-3">
              {activeIncident.rcaReport.preventiveActions.map((action, idx) => (
                <div key={idx} className="flex gap-2.5 items-start text-xs text-gray-300">
                  <FileCheck2 className="w-4 h-4 text-indigo-400 shrink-0 mt-0.5" />
                  <p className="leading-relaxed">{action}</p>
                </div>
              ))}
            </div>
          </div>

        </div>

        {/* Seal Watermark (Visible in printed copy or preview) */}
        <div className="border-t border-white/10 pt-6 flex justify-between items-center text-[10px] text-gray-500 font-mono">
          <span>REPORT STAMP: SMARTOPS-RCA-{activeIncident.id}-INGESTED</span>
          <div className="flex items-center gap-1 text-indigo-400">
            <Cpu className="w-3.5 h-3.5" />
            <span>AI Verified Remediations</span>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Reports;
