services:
  - type: web
    name: smartops-ai-backend
    env: docker
    region: oregon
    plan: free
    branch: main
    dockerContext: Project/backend
    dockerfilePath: Project/backend/Dockerfile
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        value: 8002
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        value: sqlite:///./smartops_ai.db
      - key: CORS_ORIGINS
        value: "*"
    healthCheckPath: /health
